export class GraphicModel {
    idobjetivevalue: number;
    idobjectivo: number;
    meta: string;
    idnumerador: number;
    descripcion_numerador: string;
    valor_numerador: string;
    iddenominador: number;
    descripcion_denominador: string;
    valor_denominador: string;
    idusuario: number;
    fullname: string;
    idprincipio: number;
    descripcionprincipio: string;
    idindicador: number;
    descripcionindicador: string;
    codigoindicador: string;
    operacion: string;
    commentario: string;
    resultado_indicador: string;
    graficotipo: string;
    logica: string;
    variablesgrafico: string[];
    resultado_grafico: string[];
    cumplimiento: boolean;
    status: boolean;
    fechacreacion: Date;
    fechamodificacion: Date;
    idclasificacion: number;
    action: string;
    relacionproporcion: string;
    unidades_indicador: string;
    unidades_numerador: string;
    unidades_denominador: string;

    constructor() {
        this.idobjetivevalue = 0;
        this.idobjectivo = 0;
        this.meta = '';
        this.idnumerador = 0;
        this.descripcion_numerador = '';
        this.valor_numerador = '';
        this.iddenominador = 0;
        this.descripcion_denominador = '';
        this.valor_denominador = '';
        this.idusuario = 0;
        this.fullname = '';
        this.graficotipo = '';
        this.commentario = '';
        this.operacion = '';
        this.logica = '';
        this.idprincipio = 0;
        this.descripcionprincipio = '';
        this.idindicador = 0;
        this.idclasificacion = 0;
        this.descripcionindicador = '';
        this.codigoindicador = '';
        this.resultado_indicador = '';
        this.relacionproporcion = '';
        this.action = '';
        this.unidades_numerador = '';
        this.unidades_indicador = '';
        this.unidades_denominador = '';
        this.variablesgrafico = [];
        this.resultado_grafico = [];
        this.cumplimiento = false;
        this.status = false;
        this.fechacreacion = new Date();
        this.fechamodificacion = new Date();
    }
}
